### ISSUE TITLE
handle setup of swap and  kernel parameter

### ISSUE THREAD

**Issue by gthieleb** [alvistack/ansible-role-hibernate#1]
Does this role manage the setup of swap and the configuration of the required kernel parameter (resume, ...)?

**Comment by hswong3i** [comment]
Here we don't handle the creation of swap partition nor corresponding kernel parameters, please refer to https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate for more detail.

### TL;DR

With today UEFI based + SSD hardware, the disk layout for UEFI is a bit tricky, e.g. you need a 1st partition with `fat32` for UEFI data. Now a day I will utilize OS installation procedure for initial disk partitioning by its auto detection, then retouch it with non-LVM based swap partition for hibernate.

I usually enable hibernate for my co-worker's Dell notebook with Ubuntu 22.04 Desktop. BTW, with default OS installation procedure it will only create a small (~= 4GB) LVM-based swap partition which is not ideal. Therefore after installation, before initial reboot, I will manually retouch the disk with following procedure:
1. `swapoff -a`
2. `lvremove` the swap LVM partition
3. `fsck -fyv` + `resize2fs 50G` the root LVM partition
4. `lvresize -l50%VG` the root LVM partition
5. Using `gparted` to resize and create a 16GB (or as large as your main memory) swap non-LVM partition at the tail of disk (Using GUI because I couldn't remember all corresponding CLI commands and hope to utilize some auto correction provided by `gparted`)
6. `lvresize -l95%VG` the root LVM partition (5% remaining in case I hope to have LVM snapshot for backup at someday later)
7. `resize2fs` + `fsck -fyv` the root LVM partition to entire LV size (which is now 95% of its VG)
8. `blkid` to get all partition UUID
9. Manually mount the root LVM partition, retouch both `/etc/fstab` and `/etc/default/grub` with corresponding parameters for hibernate, e.g. `resume=UUID=xxx`
10. Reboot, `apt update && apt -y full-upgrade` to latest kernel, reboot, `update-grub && update-initramfs -c -k all`, running this Ansible Role for any else tricky parameters, reboot, test hibernate with `systemctl hibernate`

The key point for why this Ansible Role DON'T handle swap partition creation goes to above step 1 to 9... If the automatic detection goes wrong you will result with a non-bootable system + broken data.

Some OS installation also coming with different default disk partition layout, so I couldn't always assume with UEFI + LVM single root partition as Ubuntu 22.04 Desktop. This also a troublesome for automatic detection by Ansible.

So my overall logic would be:
1. Manually create and manage the required non-LVM swap partition by expert
2. Using https://github.com/alvistack/ansible-role-hibernate to handle tricky hibernate related parameters
3. Using https://github.com/alvistack/ansible-role-swap to ensure `vm.swappiness=0` to avoid non-hibernate read/write to this SSD non-LVM swap partition (as much as possible)
4. Using https://github.com/alvistack/ansible-role-zram_generator to create a additional zram based swap as spare (in case we really burst in memory, e.g. opening 50+ tabs with Firefox and Chrome)

P.S. I guess we could well document above steps that I used daily in `README.md` as live example + code snippet + screenshot as example.
